version: '3'
services:
  docker-registry:
    image: registry:2
    restart : always
    container_name: docker-registry
    ports:
    - "80:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data